### ISSUE TITLE
Documentation error?

### ISSUE THREAD

**Issue by sanity** [rofrol/react-starter-kit#1]
From the front page:

> Install python in your PATH (needed for livereactload - hot reloading), then

> npm i

```
/tmp $ npm i
npm ERR! install Couldn't read dependencies
npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "i"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! path /private/tmp/package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -2

npm ERR! package.json ENOENT, open '/private/tmp/package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/npm-debug.log
```

I'm sure I'm doing something really dumb here (I'm a JavaScript newbie), but still, if I got stuck here then others probably have too.

**Comment by sanity** [comment]
Ok, duh, I'm supposed to clone the git directory and run `npm i` from there.  I'm sure it seems obvious to most people, but might help to spell this out for newbies like me.

**Comment by rofrol** [comment]
Thanks for suggestion. BTW. python isn't needed anymore
